# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build pull request

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
#      - name: Install dependencies
#        run: |
#          sudo apt update && sudo apt install -y libc6-dev libcairo2-dev libgdiplus libx11-dev
      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.3
        
        with:
          file: |
            "**/*.csproj", "**/*.nuspec", "**/AssemblyInfo.cs"
          version: bump-build


      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test
      - name: Pack
        if: ${{ success() && !github.base_ref }}
        run: |
          dotnet pack src/GradsSharp/GradsSharp.csproj --no-build --verbosity normal -c Release -o artifacts/
          dotnet pack src/GradsSharp.DrawingEngine.Cairo/GradsSharp.DrawingEngine.Cairo.csproj --no-build --verbosity normal -c Release -o artifacts/        
          dotnet pack src/GradsSharp.DataReader.GFS/GradsSharp.DataReader.GFS.csproj --no-build --verbosity normal -c Release -o artifacts/        
